# Generated by Django 3.1.4 on 2021-01-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('registration_fees', models.FloatField()),
                ('event_categories', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=250)),
                ('event_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
