# Generated by Django 3.1.5 on 2021-01-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('registration_fees', models.FloatField()),
                ('event_categories', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=250)),
                ('event_contact', models.CharField(max_length=15)),
                ('event_start_time', models.DateField(blank=True, null=True)),
                ('event_end_time', models.DateField(blank=True, null=True)),
                ('event_iscompleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('institute_name', models.CharField(max_length=50)),
                ('github_profile', models.CharField(max_length=50)),
            ],
        ),
    ]
