# Generated by Django 3.1.5 on 2021-01-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('App Development', 'App Development'), ('Others', 'Others')], default='others', max_length=35),
        ),
    ]
