# Generated by Django 3.1.5 on 2021-01-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.CharField(choices=[('Hackathon', 'Hackathon'), ('UI/UX', 'UI/UX'), ('TinkerHub.py', 'TinkerHub.py'), ('Java BootCamp', 'Java BootCamp'), ('HTML, CSS and JS', 'HTML, CSS and JS')], default='Select a Option', max_length=25),
        ),
    ]
