# Generated by Django 3.1.5 on 2021-01-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_event_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_categories',
        ),
    ]
