# Generated by Django 3.1.4 on 2021-01-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_auto_20210102_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
