# Generated by Django 3.1.5 on 2021-01-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_registration_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
    ]
