# Generated by Django 3.1.5 on 2021-01-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_remove_event_event_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.CharField(choices=[(1, 'UI/UX'), (2, 'Hackathon')], default='Select a Option', max_length=25),
        ),
    ]
