# Generated by Django 3.1.5 on 2021-01-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_registration_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.CharField(choices=[(1, 'UI/UX'), (2, 'Hackathon'), (3, 'TinkerHub.py')], default='Select a Option', max_length=25),
        ),
    ]
