# Generated by Django 3.1.4 on 2021-01-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_auto_20210102_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('institute_name', models.CharField(max_length=50)),
                ('github_profile', models.CharField(max_length=50)),
            ],
        ),
    ]
