# Generated by Django 3.1.4 on 2021-01-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Registration',
        ),
    ]
