# Generated by Django 3.1.4 on 2021-01-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_auto_20210103_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.CharField(choices=[(1, 'Hackathon'), (2, 'Django Bootcamp'), (3, 'UI/UX')], default='Select a Option', max_length=25),
        ),
    ]
